version: "0.0.1"
services:
  app:
    container_name: fluent_server
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3001"
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodata:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles
volumes:
  mongodata:
